//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningMaterials.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearnEntities : DbContext
    {
        private static LearnEntities _context;

        public LearnEntities()
            : base("name=LearnEntities")
        {
        }

        public static LearnEntities Context
        {
            get
            {
                if (_context == null)
                    _context = new LearnEntities();

                return _context;
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Learn> Learn { get; set; }
        public virtual DbSet<SourceLore> SourceLore { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
