//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningMaterials.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learn
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DateReading { get; set; }
        public string Image { get; set; }
        public int SourceLoreId { get; set; }
        public bool IsStudying { get; set; }

        public string StudiedText
        {
            get
            {
                return (IsStudying) ? "Изучен" : "Не изучен";
            }
        }

        public virtual SourceLore SourceLore { get; set; }
    }
}
